version: '3'
services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    command: ["/app/main"]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    depends_on:
      - mongo

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - 'mongodb_data:/data/db'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  mongo-seed:
    build: ./mongo-seed
    container_name: mongo-seed
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    depends_on:
      - mongo

volumes:
  mongodb_data:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
