version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    command: ["/app/main"]
  mongodb:
    image: 'bitnami/mongodb:3.6'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
